---
apiVersion: v1
kind: Service
metadata:
  name: flux-helm-operator
  namespace: flux
  labels:
    app: flux-helm-operator
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flux-helm-operator
