---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: flux
  labels:
    app: flux-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flux-helm-operator
    spec:
      serviceAccountName: flux-helm-operator
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
      containers:
        - name: flux-helm-operator
          image: docker.io/fluxcd/helm-operator:1.0.0-rc7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3030
          livenessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
          args:
            - --enabled-helm-versions=v2,v3
            - --log-format=json
            - --git-timeout=20s
            - --git-poll-interval=5m
            - --charts-sync-interval=3m
            - --update-chart-deps=true
            - --log-release-diffs=false
            - --workers=2
            - --tiller-namespace=kube-system
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
