---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: server
      containers:
      - image: ricoberger/gitops-using-flux:master-bbb773d
        name: server
