---
resources:
  - flux/flux-helm-operator-cr.yaml
  - flux/flux-helm-operator-deploy.yaml
  - flux/flux-helm-operator-sa.yaml
  - flux/flux-helm-operator-svc.yaml
  - flux/flux-helm-release-crd.yaml
  - prometheus/prometheus-operator-helm.yaml
  - prometheus/prometheus-operator-ns.yaml
  - server/server-deploy.yaml
  - server/server-ns.yaml
  - server/server-sm.yaml
  - server/server-svc.yaml
