---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server
  labels:
    app: server
    release: prometheus-operator
  namespace: server
spec:
  endpoints:
    - interval: 10s
      scrapeTimeout: 10s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - server
  selector:
    matchLabels:
      app: server
