---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
  labels:
    app: server
  annotations:
    fluxcd.io/automated: "false"
spec:
  # replicas: <KUSTOMIZE>
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          # image: <KUSTOMIZE>
          imagePullPolicy: IfNotPresent
          # args: <KUSTOMIZE>
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          # resources: <KUSTOMIZE>
