---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.server: "glob:master-*"
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: server
          image: ricoberger/gitops-using-flux:master-98257c2
          args:
            - --log.level=info
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
