env:
  image_name: ricoberger/gitops-using-flux

name: docker

on:
  push:
    paths-ignore:
      - 'k8s/**'

jobs:
  docker:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${image_name}:$(git --no-pager describe --tags --always) .

      - name: Tag (master)
        if: github.ref == 'refs/heads/master'
        run: docker tag ${image_name}:$(git --no-pager describe --tags --always) ${image_name}:master-$(git --no-pager describe --tags --always) &&
          docker tag ${image_name}:$(git --no-pager describe --tags --always) ${image_name}:latest

      - name: Tag (git tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag ${image_name}:$(git --no-pager describe --tags --always) ${image_name}:$(git --no-pager describe --tags --always)

      - name: Push
        run: docker push ${image_name}
